
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READLINE = 26;
  public static final int GE = 37;
  public static final int DOUBLE = 10;
  public static final int LPAREN = 54;
  public static final int PRIVATE = 23;
  public static final int CONTINUE = 8;
  public static final int INT = 16;
  public static final int MULTIPLYASSIGN = 41;
  public static final int MINUS = 47;
  public static final int FOR = 13;
  public static final int RPAREN = 55;
  public static final int PLUSASSIGN = 39;
  public static final int DEFINE = 9;
  public static final int SEMICOLON = 53;
  public static final int NOT = 52;
  public static final int AND = 43;
  public static final int LT = 35;
  public static final int READINTEGER = 25;
  public static final int MINUSASSIGN = 40;
  public static final int OR = 44;
  public static final int COMMA = 51;
  public static final int BOOL = 2;
  public static final int CLASS = 7;
  public static final int DIV = 49;
  public static final int NEWARRAY = 20;
  public static final int PLUS = 46;
  public static final int DIVIDEASSIGN = 42;
  public static final int ASSIGN = 38;
  public static final int IF = 14;
  public static final int THIS = 29;
  public static final int DOT = 50;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int DOUBLELITERAL = 62;
  public static final int TRUE = 64;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int LCURLY = 58;
  public static final int NULL = 21;
  public static final int MOD = 45;
  public static final int IDENT = 60;
  public static final int BREAK = 5;
  public static final int VOID = 30;
  public static final int EQ = 32;
  public static final int DTOI = 11;
  public static final int RCURLY = 59;
  public static final int LBRACK = 56;
  public static final int INTLITERAL = 61;
  public static final int IMPORT = 15;
  public static final int ELSE = 12;
  public static final int RBRACK = 57;
  public static final int ITOD = 18;
  public static final int ITOB = 17;
  public static final int WHILE = 31;
  public static final int __FUNC__ = 3;
  public static final int PUBLIC = 24;
  public static final int BTOI = 6;
  public static final int NE = 33;
  public static final int PROD = 48;
  public static final int STRING = 28;
  public static final int STRINGLITERAL = 63;
  public static final int FALSE = 65;
  public static final int GT = 36;
  public static final int __LINE__ = 4;
  public static final int PRINT = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "__FUNC__",
  "__LINE__",
  "BREAK",
  "BTOI",
  "CLASS",
  "CONTINUE",
  "DEFINE",
  "DOUBLE",
  "DTOI",
  "ELSE",
  "FOR",
  "IF",
  "IMPORT",
  "INT",
  "ITOB",
  "ITOD",
  "NEW",
  "NEWARRAY",
  "NULL",
  "PRINT",
  "PRIVATE",
  "PUBLIC",
  "READINTEGER",
  "READLINE",
  "RETURN",
  "STRING",
  "THIS",
  "VOID",
  "WHILE",
  "EQ",
  "NE",
  "LE",
  "LT",
  "GT",
  "GE",
  "ASSIGN",
  "PLUSASSIGN",
  "MINUSASSIGN",
  "MULTIPLYASSIGN",
  "DIVIDEASSIGN",
  "AND",
  "OR",
  "MOD",
  "PLUS",
  "MINUS",
  "PROD",
  "DIV",
  "DOT",
  "COMMA",
  "NOT",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LCURLY",
  "RCURLY",
  "IDENT",
  "INTLITERAL",
  "DOUBLELITERAL",
  "STRINGLITERAL",
  "TRUE",
  "FALSE"
  };
}

