
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 47;
  public static final int READLINE = 25;
  public static final int DOUBLE = 4;
  public static final int LPAREN = 58;
  public static final int SEMI = 52;
  public static final int PRIVATE = 30;
  public static final int CONTINUE = 20;
  public static final int T_DOUBLELITERAL = 35;
  public static final int INTERFACE = 9;
  public static final int INT = 3;
  public static final int LESS = 44;
  public static final int MINUS = 40;
  public static final int FOR = 14;
  public static final int OPENAC = 60;
  public static final int RPAREN = 59;
  public static final int AND = 50;
  public static final int NOT = 49;
  public static final int READINTEGER = 24;
  public static final int OR = 51;
  public static final int COMMA = 53;
  public static final int BOOL = 5;
  public static final int CLASS = 8;
  public static final int T_INTLITERAL = 34;
  public static final int DIV = 42;
  public static final int BRACK = 56;
  public static final int NEWARRAY = 22;
  public static final int PLUS = 39;
  public static final int LESSEQ = 45;
  public static final int ASSIGN = 37;
  public static final int IF = 16;
  public static final int THIS = 11;
  public static final int DOT = 54;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int T_STRINGLITERAL = 36;
  public static final int NULL = 10;
  public static final int MOD = 43;
  public static final int BREAK = 19;
  public static final int VOID = 2;
  public static final int EQ = 38;
  public static final int DTOI = 26;
  public static final int LBRACK = 55;
  public static final int ELSE = 17;
  public static final int PROTECTED = 31;
  public static final int RBRACK = 57;
  public static final int ITOD = 27;
  public static final int ITOB = 29;
  public static final int WHILE = 15;
  public static final int PUBLIC = 32;
  public static final int EXTENDS = 12;
  public static final int BTOI = 28;
  public static final int PROD = 41;
  public static final int STRING = 6;
  public static final int T_BOOLEANLITERAL = 7;
  public static final int CLOSEAC = 61;
  public static final int GT = 46;
  public static final int IMPLEMENTS = 13;
  public static final int T_ID = 33;
  public static final int PRINT = 23;
  public static final int NOTEQ = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "T_BOOLEANLITERAL",
  "CLASS",
  "INTERFACE",
  "NULL",
  "THIS",
  "EXTENDS",
  "IMPLEMENTS",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "NEW",
  "NEWARRAY",
  "PRINT",
  "READINTEGER",
  "READLINE",
  "DTOI",
  "ITOD",
  "BTOI",
  "ITOB",
  "PRIVATE",
  "PROTECTED",
  "PUBLIC",
  "T_ID",
  "T_INTLITERAL",
  "T_DOUBLELITERAL",
  "T_STRINGLITERAL",
  "ASSIGN",
  "EQ",
  "PLUS",
  "MINUS",
  "PROD",
  "DIV",
  "MOD",
  "LESS",
  "LESSEQ",
  "GT",
  "GTEQ",
  "NOTEQ",
  "NOT",
  "AND",
  "OR",
  "SEMI",
  "COMMA",
  "DOT",
  "LBRACK",
  "BRACK",
  "RBRACK",
  "LPAREN",
  "RPAREN",
  "OPENAC",
  "CLOSEAC"
  };
}

